# Generated by Django 4.1.2 on 2022-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('federal_district', models.CharField(max_length=50, verbose_name='Федеральный округ')),
                ('region', models.CharField(max_length=50, verbose_name='Область')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Номер дома')),
                ('block', models.CharField(max_length=50, verbose_name='Блок дома')),
                ('flat', models.CharField(max_length=50, verbose_name='Номер квартиры')),
                ('geo_lat', models.FloatField(verbose_name='Географическая широта')),
                ('geo_lon', models.FloatField(verbose_name='Географическая долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['city'],
            },
        ),
    ]
