# Generated by Django 4.1.2 on 2022-10-23 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', osm_field.fields.OSMField(lat_field='latitude', lon_field='longitude', verbose_name='Локация')),
                ('latitude', osm_field.fields.LatitudeField(validators=[osm_field.validators.validate_latitude], verbose_name='Географическая широта')),
                ('longitude', osm_field.fields.LongitudeField(validators=[osm_field.validators.validate_longitude], verbose_name='Географическая долгота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['location'],
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
