# Generated by Django 4.1.2 on 2022-10-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='geo_lat',
            field=models.CharField(max_length=50, verbose_name='Географическая широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='geo_lon',
            field=models.CharField(max_length=50, verbose_name='Географическая долгота'),
        ),
    ]
