# Generated by Django 4.1.2 on 2022-10-22 09:33

from django.db import migrations
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['location'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='latitude',
            field=osm_field.fields.LatitudeField(validators=[osm_field.validators.validate_latitude], verbose_name='Географическая широта'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='location',
            field=osm_field.fields.OSMField(lat_field='latitude', lon_field='longitude', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='longitude',
            field=osm_field.fields.LongitudeField(validators=[osm_field.validators.validate_longitude], verbose_name='Географическая долгота'),
        ),
    ]
